{
 "title": "MirrorMaker2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "MirrorSourceConnector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic Replication Latency",
   "type": "graph",
   "description": "The time it takes records to propagate source->target",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(connect_mirror_mirrorsourceconnector_replication_latency_ms[$__interval])) by (topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Replication Record Count by Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connect_mirror_mirrorsourceconnector_record_count) by (topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Topic Record Age",
   "type": "graph",
   "description": "Age of records when they are replicated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ]
  },
  {
   "title": "Replication Byte Rate Per Second",
   "type": "graph",
   "description": "Average number of bytes/sec in replicated records",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(connect_mirror_mirrorsourceconnector_byte_rate) by (topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Replication Byte Count by Topic",
   "type": "graph",
   "description": "Byte_Count = Number of Records * Record Size",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(connect_mirror_mirrorsourceconnector_byte_count) by (topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  { "title": "MirrorCheckpointConnector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Topic Checkpoint Latency",
   "type": "graph",
   "description": "Tme it takes to replicate consumer offsets",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms[$__interval])) by (topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  }
 ]
}