{
 "title": "MSK - Dashboard 1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Value{name=\"LeaderCount\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Should be 1.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate. Should be 0.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_OneMinuteRate{name=\"UncleanLeaderElectionsPerSec\"})"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "singlestat",
   "description": "Also includes the MSK internal topics __amazon_msk_canary, __amazon_msk_canary_state, __consumer_offsets",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Should be 0.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The average amount of CPU time, per second, over the 5 minutes (in seconds)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (node_cpu_seconds_total{}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Byte Rate Per Second",
   "type": "graph",
   "description": "Aggregated incoming and outgoing byte rate across brokers.\nBytesInPerSec is the metric that monitors the write throughput of producers into each broker.\nBytesOutPerSec is the number of bytes per second sent to clients.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\"})",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\"})",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "description": "Total messages ingested across brokers",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\"})",
     "legendFormat": "Messages In Per Second"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Number of total vs failed producer requests being to a broker per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"TotalProduceRequestsPerSec\"})",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedProduceRequestsPerSec\"})",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Comparing the total vs failed fetch requests made by the client and replicas.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"TotalFetchRequestsPerSec\"})",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"FailedFetchRequestsPerSec\"})",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Consumer Lag By Topic",
   "type": "graph",
   "description": "The aggregated offset lag for all the partitions in a topic. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_group_ConsumerLagMetrics_Value{ name=\"SumOffsetLag\", topic!=\"\",  topic!~\".*source.*\", topic!~\".*__.*\", topic!~\".*heartbeat.*\"}) by (groupId, topic) ",
     "legendFormat": "{{groupId}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "The rate of requests for producers, consumers, and followers across brokers.\nIf RequestsPerSec remains high, then increase the batch size on your producers, consumers, and/or number of brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_OneMinuteRate{name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "The average percentage of the time the network processors are idle. \n\nRecommended value between 0 and 100%, ideally > 0.3 (30%)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "The average percentage of the time the request handler threads are idle.\nRecommended value between 0 and 1 (100%), ideally > 0.3 (30%)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_OneMinuteRate{name=\"RequestHandlerAvgIdlePercent\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network: ErrorsPerSec",
   "type": "graph",
   "description": "Number of errors in responses counted per-request-type, per-error-code.\n\nIf network throughput decreases without an increase in error rate, this can indicate the need to scale data consumers up, whereas dropped packets can indicate a hardware issue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(rate(kafka_network_RequestMetrics_Count{name=\"ErrorsPerSec\"}[5m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "MessagesInPerSec by Business Topic",
   "type": "graph",
   "description": "Total messages ingested across business topics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\", topic!=\"\",  topic!~\".*source.*\", topic!~\".*__.*\", topic!~\".*heartbeat.*\"}) without(instance)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Byte In by Business Topic",
   "type": "graph",
   "description": "Aggregated incoming byte rate across brokers by topics.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", topic=~\".+\", topic!~\".*source.*\", topic!~\".*__.*\", topic!~\".*heartbeat.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Byte Out by Business Topic",
   "type": "graph",
   "description": "Aggregated outgoing byte rate across brokers by topics.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", topic=~\".+\", topic!~\".*source.*\", topic!~\".*__.*\", topic!~\".*heartbeat.*\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "% Disk Space Used by Broker",
   "type": "graph",
   "description": "Disk space used in % per broker.\nRef: https://www.robustperception.io/filesystem-metrics-from-the-node-exporter",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/kafka/datalogs\"}/node_filesystem_size_bytes{mountpoint=\"/kafka/datalogs\"} * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "singlestat",
   "description": "Total available disk space",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 53 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/.*\"})"
    }
   ]
  }
 ]
}